name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci

    - name: Check SBOM Changes
      run: |
        echo "Generationg a copy of the SBOM folder..."
        mkdir -p sbom-tmp
        copy_sbom_files() {
            echo "Copying SBOM files..."
            rm -rf sbom-tmp/*
            cp -r sbom/* sbom-tmp/
        }
        
        clean_up() {
            echo "Removing temporary files..."
            rm current_hashes.txt new_hashes.txt
            rm -rf sbom-tmp
        }
        calculate_hashes() {
            file=$1
            echo "Removing timestamp and serialNumber from cyclonedx SBOM..."
            jq 'del(.metadata.timestamp)' sbom-tmp/cyclonedx.json > sbom-tmp/cyclonedx.json.tmp && mv sbom-tmp/cyclonedx.json.tmp sbom-tmp/cyclonedx.json
            jq 'del(.serialNumber)' sbom-tmp/cyclonedx.json > sbom-tmp/cyclonedx.json.tmp && mv sbom-tmp/cyclonedx.json.tmp sbom-tmp/cyclonedx.json
        
            echo "Removing timestamp and documentNamespace from spdx SBOM..."
            jq 'del(.creationInfo.created)' sbom-tmp/spdx.json > sbom-tmp/spdx.json.tmp && mv sbom-tmp/spdx.json.tmp sbom-tmp/spdx.json
            jq 'del(.documentNamespace)' sbom-tmp/spdx.json > sbom-tmp/spdx.json.tmp && mv sbom-tmp/spdx.json.tmp sbom-tmp/spdx.json
        
            echo "generating hashes and storing them in $file..."
            
            sha256sum sbom-tmp/cyclonedx.json >> $file
            sha256sum sbom-tmp/spdx.json >> $file
            cat $file
        }
        
        echo "Calculating current hashes..."
        copy_sbom_files
        calculate_hashes current_hashes.txt
        
        echo "Generating new SBOM..."
        npm run generate-sbom
        
        echo "Calculating new hashes..."
        copy_sbom_files
        calculate_hashes new_hashes.txt
        
        echo "Comparing hashes..."
        diff current_hashes.txt new_hashes.txt
        
        if [ $? -ne 0 ]; then
            echo "Error: SBOM hashes do not match, please run 'npm run generate-sbom' locally and commit the changes."
            clean_up    
            exit 1
        fi
        
        echo "SBOM hashes match!"
        clean_up
        exit 0

    - run: npm test --if-present